@startuml
actor Player
participant GameSystem as System

== Setup ==
Player -> System : placeWorker(positionA)
Player -> System : placeWorker(positionB)
Player -> System : confirmPlacement()

== Game Play ==
loop Until Winner
  Player -> System : selectWorker(workerID)

  alt If adjacent field is valid
    Player -> System : moveWorker(workerID, newPosition)
    System --> Player : workerMoved()

    alt If worker on level-3
      System -> Player : playerWins()
      break
    end

    alt If adjacent field is valid for building
      Player -> System : buildBlock(newPosition)
      System --> Player : blockBuilt()

      alt If building on level-3
        Player -> System : buildDome(newPosition)
        System --> Player : domeBuilt()
      end
    end
  else If no valid moves
    System -> Player : invalidMove()
  end
end
@enduml
